inherit_gem:
  switchcop: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'tmp/**/*'
    - '**/*/bundle'

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude: ["rest-api-generator.gemspec"]

Metrics/MethodLength:
  Max: 17

Metrics/AbcSize:
  Max: 25

RSpec/ExampleLength:
  Max: 6

Metrics/BlockLength:
  AllowedMethods: [ 'describe', 'context' ]